version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-7trip-local
    ports:
      - '5450:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: 7trip_local
    restart: always

  api:
    build:
      context: ./apps/api
      dockerfile: docker/Dockerfile.local
    container_name: api-7trip-local
    ports:
      - '4201:3001'
    env_file:
      - .env.local
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    depends_on:
      - db
    restart: always

  front:
    build:
      context: ./apps/front
      dockerfile: docker/Dockerfile.local
    container_name: front-7trip-local
    ports:
      - '4200:3000'
    env_file:
      - .env.local
    volumes:
      - ./apps/front:/app
      - /app/node_modules
    depends_on:
      - api
    restart: always
