version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-7trip-prod
    ports:
      - '8532:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: 7trip_prod
    restart: always

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.prod
    container_name: api-7trip-prod
    ports:
      - '8101:3001'
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

  front:
    build:
      context: ./apps/front
      dockerfile: Dockerfile.prod
    container_name: front-7trip-prod
    ports:
      - '8100:3000'
    env_file:
      - .env.prod
    depends_on:
      - api
    restart: always
