name: 🚀 Deploy DEV to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/${{ secrets.VPS_SSH_KEY_NAME }}
          chmod 600 ~/.ssh/${{ secrets.VPS_SSH_KEY_NAME }}
          ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/${{ secrets.VPS_SSH_KEY_NAME }} -p ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            echo "✅ Connexion SSH réussie"
            
            mkdir -p ~/projects/7trip/dev
            cd ~/projects/7trip/dev

            if [ ! -d ".git" ]; then
              echo "📁 Initial clone"
              git clone -b dev https://github.com/jordanolv/7trip.git .
            else
              echo "📦 Git repo already present"
            fi

            echo "📥 Pull latest code"
            git config --global --add safe.directory ~/projects/7trip/dev
            git config pull.rebase false
            git reset --hard
            git clean -fd
            git pull origin dev --allow-unrelated-histories || git fetch origin dev && git reset --hard origin/dev

            echo "🔧 Update permissions"
            sudo chown -R ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} ~/projects/7trip/dev || true

            echo "🛠️ Docker Compose DEV"
            docker compose -f docker-compose.dev.yml down || true
            docker compose -f docker-compose.dev.yml up --build -d

            echo "✅ DEV deployment finished 🎉"
          EOF

